# Generated by Django 4.2.20 on 2025-08-01 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporatePartner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner_logos/')),
                ('homepage_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Corporate Partner',
                'verbose_name_plural': 'Corporate Partners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlexibleCatalogModel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(help_text='Human friendly', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CorporatePartnerCatalog',
            fields=[
                ('flexiblecatalogmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corporate_partner_access.flexiblecatalogmodel')),
                ('course_enrollment_limit', models.PositiveIntegerField(default=0, help_text='Max enrollments allowed in this catalog.')),
                ('user_limit', models.PositiveIntegerField(default=0, help_text='Max users allowed in this catalog.')),
                ('is_self_enrollment', models.BooleanField(default=False)),
                ('available_start_date', models.DateTimeField(blank=True, null=True)),
                ('available_end_date', models.DateTimeField(blank=True, null=True)),
                ('custom_courses', models.BooleanField(default=False, help_text='If True, allows custom courses.')),
                ('authorization_additional_message', models.TextField(blank=True, null=True)),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('catalog_alternative_link', models.URLField(blank=True, null=True)),
                ('corporate_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='corporate_partner_access.corporatepartner')),
            ],
            options={
                'verbose_name': 'Corporate Partner Catalog',
                'verbose_name_plural': 'Corporate Partner Catalogs',
                'ordering': ['name'],
            },
            bases=('corporate_partner_access.flexiblecatalogmodel',),
        ),
        migrations.CreateModel(
            name='CorporatePartnerCatalogLearner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate_partner_access.corporatepartnercatalog')),
            ],
            options={
                'verbose_name': 'Corporate Partner Catalog Learner',
                'verbose_name_plural': 'Corporate Partner Catalog Learners',
                'unique_together': {('catalog', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CorporatePartnerCatalogEmailRegex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regex', models.CharField(help_text='Regex pattern for email validation.', max_length=255)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_regexes', to='corporate_partner_access.corporatepartnercatalog')),
            ],
        ),
        migrations.CreateModel(
            name='CorporatePartnerCatalogCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0, help_text='Ordering of the course within the catalog.')),
                ('course_overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_overviews.courseoverview')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate_partner_access.corporatepartnercatalog')),
            ],
            options={
                'verbose_name': 'Corporate Partner Catalog Course',
                'verbose_name_plural': 'Corporate Partner Catalog Courses',
                'ordering': ['position'],
                'unique_together': {('catalog', 'course_overview')},
            },
        ),
        migrations.AddField(
            model_name='corporatepartnercatalog',
            name='courses',
            field=models.ManyToManyField(related_name='partner_catalogs', through='corporate_partner_access.CorporatePartnerCatalogCourse', to='course_overviews.courseoverview'),
        ),
        migrations.AddField(
            model_name='corporatepartnercatalog',
            name='learners',
            field=models.ManyToManyField(related_name='enrolled_catalogs', through='corporate_partner_access.CorporatePartnerCatalogLearner', to=settings.AUTH_USER_MODEL),
        ),
    ]
