# Generated by Django 4.2.20 on 2025-08-28 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corporate_partner_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporatePartnerManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('partner_manager', 'Partner Manager'), ('partner_viewer', 'Partner Viewer')], max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_managers', to='corporate_partner_access.corporatepartner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corporate Partner Catalog Manager',
                'verbose_name_plural': 'Corporate Partner Catalog Managers',
                'unique_together': {('partner', 'user')},
            },
        ),
        migrations.AddField(
            model_name='corporatepartner',
            name='managers',
            field=models.ManyToManyField(related_name='corporate_partners', through='corporate_partner_access.CorporatePartnerManager', to=settings.AUTH_USER_MODEL),
        ),
    ]
