# Generated by Django 4.2.20 on 2025-08-27 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corporate_partner_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCourseEnrollmentAllowed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Sent'), (20, 'Accepted'), (30, 'Declined')], default=10, help_text='Status of the course enrollment invitation.')),
                ('invite_email', models.EmailField(blank=True, help_text='Invitation email address.', max_length=254, null=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('catalog_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_invites', to='corporate_partner_access.corporatepartnercatalogcourse')),
                ('invited_by', models.ForeignKey(blank=True, help_text='Who created/sent the invite.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_enrollment_invites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Linked user. May be null if no user exists for invite_email; will be set once a user with this email accepts/declines.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_course_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cp_course_enrl_allowed',
                'indexes': [models.Index(django.db.models.functions.text.Lower('invite_email'), name='cpcea_email_ci_idx'), models.Index(fields=['user'], name='cpcea_user_idx'), models.Index(fields=['catalog_course', 'status'], name='cpcea_course_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='catalogcourseenrollmentallowed',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('catalog_course', 'user'), name='cpcea_unique_course_user'),
        ),
        migrations.AddConstraint(
            model_name='catalogcourseenrollmentallowed',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('invite_email'), models.F('catalog_course'), condition=models.Q(('invite_email__isnull', False)), name='cpcea_unique_course_invite_email_ci'),
        ),
        migrations.AddConstraint(
            model_name='catalogcourseenrollmentallowed',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('invite_email__isnull', False), _connector='OR'), name='cpcea_user_or_email_required'),
        ),
        migrations.AddConstraint(
            model_name='catalogcourseenrollmentallowed',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 10), ('accepted_at__isnull', True), ('declined_at__isnull', True)), models.Q(('status', 20), ('accepted_at__isnull', False), ('declined_at__isnull', True)), models.Q(('status', 30), ('declined_at__isnull', False), ('accepted_at__isnull', True)), _connector='OR'), name='cpcea_status_timestamp_consistency'),
        ),
    ]
