# Generated by Django 4.2.20 on 2025-08-19 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("corporate_partner_access", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corporatepartnercatalogcourse",
            name="catalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_courses",
                to="corporate_partner_access.corporatepartnercatalog",
            ),
        ),
        migrations.AlterField(
            model_name="corporatepartnercataloglearner",
            name="catalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_learners",
                to="corporate_partner_access.corporatepartnercatalog",
            ),
        ),
    ]
