# Generated by Django 4.2.20 on 2025-08-28 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corporate_partner_access', '0003_add_manager_models_and_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCourseEnrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('catalog_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='corporate_partner_access.corporatepartnercatalogcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='corporate_p_user_id_f7050f_idx'), models.Index(fields=['catalog_course'], name='corporate_p_catalog_3d9d1b_idx'), models.Index(fields=['user', 'active'], name='corporate_p_user_id_eb48a5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='catalogcourseenrollment',
            constraint=models.UniqueConstraint(fields=('user', 'catalog_course'), name='cpcea_unique_user_catalog_course_enrollment'),
        ),
    ]
