# Generated by Django 4.2.20 on 2025-09-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_partner_access', '0004_catalogcourseenrollment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatepartnercatalogcourse',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_courses', to='corporate_partner_access.corporatepartnercatalog'),
        ),
        migrations.AlterField(
            model_name='corporatepartnercataloglearner',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_learners', to='corporate_partner_access.corporatepartnercatalog'),
        ),
    ]
