# Generated by Django 4.2.20 on 2025-10-19 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flex_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0004_auto_20230727_2054'),
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0, help_text='Ordering of the course within the catalog.')),
            ],
            options={
                'verbose_name': 'Catalog Course',
                'verbose_name_plural': 'Catalog Courses',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CatalogLearner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catalog Learner',
                'verbose_name_plural': 'Catalog Learners',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Corporate Partner',
                'verbose_name_plural': 'Corporate Partners',
                'ordering': ['organization__short_name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerCatalog',
            fields=[
                ('flexiblecatalogmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_catalog.flexiblecatalogmodel')),
                ('course_enrollments_limit', models.PositiveIntegerField(default=0, help_text='Limit of enrollments per course.')),
                ('user_limit', models.PositiveIntegerField(default=0, help_text='Limit for the number of users that can enroll.')),
                ('is_self_enrollment', models.BooleanField(default=False)),
                ('available_start_date', models.DateTimeField()),
                ('available_end_date', models.DateTimeField()),
                ('authorization_message', models.TextField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='partner_catalog.partner')),
            ],
            options={
                'verbose_name': 'Partner Catalog',
                'verbose_name_plural': 'Partner Catalogs',
                'ordering': ['name'],
            },
            bases=('flex_catalog.flexiblecatalogmodel',),
        ),
        migrations.CreateModel(
            name='CatalogLearnerInvitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invite_email', models.EmailField(blank=True, help_text='Email address to which the invitation was sent.', max_length=254, null=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Sent'), (20, 'Accepted'), (30, 'Declined'), (40, 'Removed')], default=10, help_text='Current status of the learner invitation.')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner_catalog.partnercatalog')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_learner_invitations', to=settings.AUTH_USER_MODEL)),
                ('learner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_history', to='partner_catalog.cataloglearner')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_learner_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learner_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catalog Learner Invitation',
                'verbose_name_plural': 'Catalog Learner Invitations',
            },
        ),
        migrations.AddField(
            model_name='cataloglearner',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_learners', to='partner_catalog.partnercatalog'),
        ),
        migrations.AddField(
            model_name='cataloglearner',
            name='current_invitation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='current_for_learner', to='partner_catalog.cataloglearnerinvitation'),
        ),
        migrations.AddField(
            model_name='cataloglearner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CatalogEmailRegex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regex', models.CharField(help_text='Regex pattern for email validation.', max_length=500)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_email_regexes', to='partner_catalog.partnercatalog')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogCourseEnrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('catalog_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='partner_catalog.catalogcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='catalogcourse',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_courses', to='partner_catalog.partnercatalog'),
        ),
        migrations.AddField(
            model_name='catalogcourse',
            name='course_overview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_overviews.courseoverview'),
        ),
        migrations.CreateModel(
            name='CatalogManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_managers', to='partner_catalog.partnercatalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catalog Manager',
                'verbose_name_plural': 'Catalog Managers',
                'indexes': [models.Index(fields=['catalog', 'user'], name='partner_cat_catalog_861346_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='catalogmanager',
            constraint=models.UniqueConstraint(fields=('catalog', 'user'), name='pcm_unique_catalog_manager'),
        ),
        migrations.AddIndex(
            model_name='cataloglearnerinvitation',
            index=models.Index(fields=['catalog', 'user'], name='partner_cat_catalog_aa09ae_idx'),
        ),
        migrations.AddIndex(
            model_name='cataloglearnerinvitation',
            index=models.Index(fields=['catalog', 'invited_at'], name='partner_cat_catalog_7adb65_idx'),
        ),
        migrations.AddIndex(
            model_name='cataloglearnerinvitation',
            index=models.Index(fields=['accepted_at'], name='partner_cat_accepte_9ca35e_idx'),
        ),
        migrations.AddIndex(
            model_name='cataloglearnerinvitation',
            index=models.Index(fields=['declined_at'], name='partner_cat_decline_36e600_idx'),
        ),
        migrations.AddIndex(
            model_name='cataloglearnerinvitation',
            index=models.Index(fields=['removed_at'], name='partner_cat_removed_19c8af_idx'),
        ),
        migrations.AddConstraint(
            model_name='cataloglearnerinvitation',
            constraint=models.CheckConstraint(check=models.Q(('accepted_at__isnull', False), ('declined_at__isnull', False), _negated=True), name='cla_not_both_accepted_and_declined'),
        ),
        migrations.AddConstraint(
            model_name='cataloglearnerinvitation',
            constraint=models.CheckConstraint(check=models.Q(('removed_at__isnull', True), ('accepted_at__isnull', False), _connector='OR'), name='cla_removed_implies_accepted'),
        ),
        migrations.AddIndex(
            model_name='cataloglearner',
            index=models.Index(fields=['catalog', 'user'], name='partner_cat_catalog_135937_idx'),
        ),
        migrations.AddConstraint(
            model_name='cataloglearner',
            constraint=models.UniqueConstraint(fields=('catalog', 'user'), name='pcl_unique_catalog_learner'),
        ),
        migrations.AddIndex(
            model_name='catalogcourseenrollment',
            index=models.Index(fields=['user'], name='partner_cat_user_id_dce165_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogcourseenrollment',
            index=models.Index(fields=['catalog_course'], name='partner_cat_catalog_558875_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogcourseenrollment',
            index=models.Index(fields=['user', 'active'], name='partner_cat_user_id_ccb02c_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogcourseenrollment',
            constraint=models.UniqueConstraint(fields=('user', 'catalog_course'), name='pcce_unique_user_catalog_course_enrollment'),
        ),
        migrations.AddIndex(
            model_name='catalogcourse',
            index=models.Index(fields=['catalog', 'course_overview'], name='catalog_course_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogcourse',
            constraint=models.UniqueConstraint(fields=('catalog', 'course_overview'), name='pcc_unique_catalog_course'),
        ),
    ]
