# Generated by Django 4.2.20 on 2025-10-31 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flex_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
        ('partner_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCatalog',
            fields=[
                ('flexiblecatalogmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_catalog.flexiblecatalogmodel')),
            ],
            options={
                'verbose_name': 'Base Catalog',
                'verbose_name_plural': 'Base Catalogs',
            },
            bases=('flex_catalog.flexiblecatalogmodel',),
        ),
        migrations.CreateModel(
            name='BaseCatalogCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the course was added to the base catalog')),
                ('added_by', models.ForeignKey(blank=True, help_text='User who added the course to the base catalog', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('base_catalog', models.ForeignKey(help_text='Base catalog this course belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='base_catalog_courses', to='partner_catalog.basecatalog')),
                ('course_overview', models.ForeignKey(help_text='Course that is part of the base catalog', on_delete=django.db.models.deletion.CASCADE, related_name='base_catalog_entry', to='course_overviews.courseoverview')),
            ],
            options={
                'verbose_name': 'Base Catalog Course',
                'verbose_name_plural': 'Base Catalog Courses',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddField(
            model_name='basecatalog',
            name='courses',
            field=models.ManyToManyField(related_name='base_catalogs', through='partner_catalog.BaseCatalogCourse', to='course_overviews.courseoverview'),
        ),
    ]
