# Generated by Django 4.2.20 on 2025-10-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cataloglearnerinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', [10, 20])), fields=('catalog', 'invite_email'), name='cla_unique_active_invitation'),
        ),
    ]
