# Generated by Django 4.2.20 on 2025-10-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
        ('partner_catalog', '0002_cataloglearnerinvitation_cla_unique_active_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercatalog',
            name='alternative_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnercatalog',
            name='courses',
            field=models.ManyToManyField(related_name='catalogs', through='partner_catalog.CatalogCourse', to='course_overviews.courseoverview'),
        ),
        migrations.AddField(
            model_name='partnercatalog',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
