# Generated by Django 4.2.20 on 2025-11-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_catalog', '0002_cataloglearnerinvitation_cla_unique_active_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercatalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='partner_catalog_images/'),
        ),
    ]
