# Generated by Django 4.2.20 on 2025-11-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_catalog', '0003_partnercatalog_alternative_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercatalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='partner_catalog_images/'),
        ),
    ]
