# Generated by Django 4.2.20 on 2025-11-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_catalog', '0005_create_base_catalog_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercatalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='partner_catalog_images/'),
        ),
    ]
