# Generated by Django 4.2.20 on 2025-12-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_catalog', '0006_partnercatalog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloglearner',
            name='gdpr_consent_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='GDPR consent status. Course enrollment is blocked until accepted.', max_length=10),
        ),
        migrations.AddField(
            model_name='cataloglearner',
            name='gdpr_consent_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when GDPR consent status was last updated.', null=True),
        ),
    ]
