# Generated by Django 4.2.20 on 2026-02-09 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
        ('partner_catalog', '0006_partnercatalog_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='catalogcourseenrollment',
            name='pcce_unique_user_catalog_course_enrollment',
        ),
        migrations.AddField(
            model_name='catalogcourseenrollment',
            name='course_overview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_catalog_enrollments', to='course_overviews.courseoverview'),
        ),
        migrations.AddIndex(
            model_name='catalogcourseenrollment',
            index=models.Index(fields=['course_overview'], name='partner_cat_course__e36e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogcourseenrollment',
            index=models.Index(fields=['catalog_course', 'course_overview', 'active'], name='partner_cat_catalog_305aa2_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogcourseenrollment',
            constraint=models.UniqueConstraint(fields=('user', 'course_overview'), name='pcce_unique_user_course_license'),
        ),
    ]
