# Generated by Django 4.2.20 on 2026-02-09 04:43

from django.db import migrations

BATCH_SIZE = 5000

def forwards(apps, schema_editor):
    Enrollment = apps.get_model("partner_catalog", "CatalogCourseEnrollment")

    qs = (
        Enrollment.objects
        .filter(course_overview__isnull=True)
        .select_related("catalog_course__course_overview")
        .only("id", "catalog_course_id")
        .order_by("id")
    )

    batch = []
    for e in qs.iterator(chunk_size=BATCH_SIZE):
        e.course_overview_id = e.catalog_course.course_overview_id
        batch.append(e)

        if len(batch) >= BATCH_SIZE:
            Enrollment.objects.bulk_update(batch, ["course_overview"])
            batch.clear()

    if batch:
        Enrollment.objects.bulk_update(batch, ["course_overview"])

def backwards(apps, schema_editor):
    Enrollment = apps.get_model("partner_catalog", "CatalogCourseEnrollment")
    Enrollment.objects.update(course_overview=None)


class Migration(migrations.Migration):
    dependencies = [
        ('partner_catalog', '0007_remove_catalogcourseenrollment_pcce_unique_user_catalog_course_enrollment_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
