# Generated by Django 4.2.20 on 2026-02-09 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
        ('partner_catalog', '0008_backfill_course_overview_on_enrollments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogcourseenrollment',
            name='course_overview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_catalog_enrollments', to='course_overviews.courseoverview'),
        ),
    ]
