# Generated by Django 4.2.20 on 2026-09-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_catalog', '0011_add_cancelled_invitation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloglearnerinvitation',
            name='last_resent_at',
            field=models.DateTimeField(blank=True, help_text='When the invitation email was last re-sent.', null=True),
        ),
        migrations.AddField(
            model_name='cataloglearnerinvitation',
            name='resend_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times the invitation email was re-sent after the original invite.'),
        ),
    ]
